apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: {{ .Values.consumer.image }}
          env:
            - name: MONGODB_URL
              value: "{{ .Values.consumer.env.MONGODB_URL }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.consumer.env.KAFKA_BOOTSTRAP_SERVERS }}"

