apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-client
  template:
    metadata:
      labels:
        app: flask-client
    spec:
      containers:
        - name: flask-client
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-client
  ports:
    - port: {{ .Values.flask.servicePort }}
      targetPort: {{ .Values.flask.port }}
  type: NodePort
